"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var courseController_1 = require("../controllers/courseController");
var router = (0, express_1.Router)();
router.post("/createcourse", courseController_1.createCourse);
router.get("/", courseController_1.getCourses);
router.get("/:courseId", courseController_1.getCourseById);
router.put("/:courseId", courseController_1.updateCourse);
router.delete("/:courseId", courseController_1.deleteCourse);
exports.default = router;
